spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xsys@2018
    url: jdbc:mysql://137.0.51.21/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell

