spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.64/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell

wechat:
  mpAppID: wxc62f541972e7736e
  mpAppsecret: b6f8c9112bad15a43948fc710ef66c32